In [1]:
import numpy as np

# Creating a numpy array 

In [2]:
array = np.array([1,2,3,3,4,5,78,56,4])
array

array([ 1,  2,  3,  3,  4,  5, 78, 56,  4])

# Checking the type of array

In [3]:
type(array)

numpy.ndarray

# Note: We can call numpy functions by using dot after the name by which we have imported numpy or we can call a numpy function by writing dot after the name of particular numpy array

In [4]:
np.max(array) , array.max()

(78, 78)

# Shape of array tells us nummer of rows and columns of our numpy array

In [5]:
array.shape

(9,)

# Reshape function changes the dimensions of array to the dimensions passed in parameters
# Note: 
Dimensions passed as a parameter should be according to the size of array i.e 1d array of elements can be converted to a 2d array of 3x3 or 9x1 or 1x9.
Or to 3d array of 3x3x1 ,  or 1x3x3 or 3x1x3 

In [6]:
array2d = np.reshape(array,(3,3))
array2d

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [78, 56,  4]])

In [7]:
array3d = np.reshape(array ,(3,1,3))
array3d

array([[[ 1,  2,  3]],

       [[ 3,  4,  5]],

       [[78, 56,  4]]])

# len() function on a numpy array gives number of rows in the array

In [8]:
len(array) , len(array2d) , len(array3d)

(9, 3, 3)

In [9]:
array1d = np.reshape(array,(1,9))
len(array1d)

1

# np.size() gives us the number of elements in that numpy array

In [10]:
np.size(array), np.size(array2d) , np.size(array3d) ,np.size(array1d)

(9, 9, 9, 9)

# Creating an n dimensional array of only zeros

In [11]:
zeros = np.zeros((4,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

We can give any dimensions in the parameter, it will create array of that dimensions

In [12]:
np.zeros((5,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Creating an n dimensional array which contains only ones

In [13]:
ones = np.ones((3,4,2))
ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

# Creating an n dimensional array which contains element of our choice

In [14]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
np.full((5,3),'Hi')

array([['Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi'],
       ['Hi', 'Hi', 'Hi']], dtype='<U2')

# Generating an evenly spaced(equally spaced) array

First two parameters specify the range and the third elemen refers to the number of elements in that array

In [16]:
np.linspace(1,10,10)  

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(2,2,2) ,np.linspace(2,20,5)

(array([2., 2.]), array([ 2. ,  6.5, 11. , 15.5, 20. ]))

# Creating an array of random numbers of given dimensions

In [18]:
np.random.random((2,3))

array([[0.34173553, 0.44764099, 0.20658007],
       [0.78215166, 0.73369381, 0.64948543]])

# Aggregation functions on a numpy array

In [19]:
np.max(array)

78

In [20]:
np.min(array)

1

In [21]:
np.mean(array)

17.333333333333332

In [22]:
np.sum(array)

156

In [23]:
np.median(array)

4.0

# Aggregation functions on multidimensional numpy arrays , axis = 0 means columnwise and axis = 1 means rowwise

In [24]:
np.max(array2d,axis= 0 )

array([78, 56,  5])

In [25]:
np.sum(array2d,axis = 1)

array([  6,  12, 138])

# Sorting a numpy array

In [26]:
np.sort(array)

array([ 1,  2,  3,  3,  4,  4,  5, 56, 78])

In [27]:
np.sort(array2d,axis = 1) #axis = 0 means sorting columns , axis = 1 means sorting rows

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 4, 56, 78]])

# Transpose of a numpy array

In [28]:
array2d

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [78, 56,  4]])

In [29]:
np.transpose(array2d)

array([[ 1,  3, 78],
       [ 2,  4, 56],
       [ 3,  5,  4]])

# Arithmetic operations on numpy arrays

In [30]:
a = np.array([4,5,33,55,67,7])
b = np.array([1,2,4,8,7,3])
a+b

array([ 5,  7, 37, 63, 74, 10])

In [31]:
a-b

array([ 3,  3, 29, 47, 60,  4])

In [32]:
a*2

array([  8,  10,  66, 110, 134,  14])

In [33]:
a*b

array([  4,  10, 132, 440, 469,  21])

In [34]:
a/b

array([4.        , 2.5       , 8.25      , 6.875     , 9.57142857,
       2.33333333])

In [35]:
a//b

array([4, 2, 8, 6, 9, 2], dtype=int32)

# Indexing

In [36]:
array[6] #gives the element at 6th index

78

In [37]:
array[1:6] #gives elements from 1st index to 6th index , excluding 6th

array([2, 3, 3, 4, 5])

In [38]:
array[-1] #gives the last element of array

4

In [39]:
array[array > 4] #gives all the elements which are greater than 4

array([ 5, 78, 56])

In [40]:
array[:] #gives all the elements

array([ 1,  2,  3,  3,  4,  5, 78, 56,  4])

# Filtering Numpy arrays

If we simply write the condition , an array of booleans will be returned, all Trues are the indices of those elements which satisfy the condition , for remaining ones False will be there.
We can use these results to fetch the elements from the original array.

In [41]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True])

In [42]:
array[array>3]

array([ 4,  5, 78, 56,  4])

In [43]:
array[array %2 == 0]

array([ 2,  4, 78, 56,  4])

In [44]:
array[array %2!=0]

array([1, 3, 3, 5])

Adding multiple conditions. (and--> & , or--> |)

In [45]:
array[(array %2!=0) & (array >2)]

array([3, 3, 5])

In [46]:
array[(array %2==0) | (array >2)]

array([ 2,  3,  3,  4,  5, 78, 56,  4])

# Updating numpy array with a condition

Replace all even elements with 0

In [47]:
array[array %2 == 0] = 0
array

array([1, 0, 3, 3, 0, 5, 0, 0, 0])

If element is 0 then replace it with 4 otherwise don't replace

this function works elementwise
np.where(condition , if condition is true then do this , else do this)

In [48]:
np.where(array == 0,4,array)

array([1, 4, 3, 3, 4, 5, 4, 4, 4])